#공통 설정

# server
server:
  port: "8080"
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
  error:
    include-stacktrace: always
    include-trace-on-error: true


  
## logging
logging:
  level:
    root: debug
    jdbc:
      audit: off
      connection: off
      resultset: debug
      resultsettable: debug
      sqlonly: debug
      sqltiming: debug
      
spring:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/


jwt:
  header: Authorization
  secret: ZGFlZmE5NWYwYTE5M2I1YmRlYmJiOTJkYjgwYzFkNjg3MzUyOGVmMzIyZmRiYTQ4ZjFiZDE2YmM2ZGRjMzczYzg1NDZiYWZhZTE0ZWM3NDllMzYwYjZkNGE1ZDUzZDRiNWJhMjIzY2FlOTJmYzZhZGMzMDE2NjlkNjk0YWZlMTY=
  token-validity-in-seconds: 3600

