# 운영
server:
  port: "8080"
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
  error:
    include-stacktrace: always
    include-trace-on-error: true

spring:
  application:
    name: bangdori_prod
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-init-sql: select 1
      validation-timeout: 2000
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 18000000
      leak-detection-threshold: 1000000

env:
  serverUrl: "http://bangdori.com/"

path:
  image: "/home/bangdoriImg"
