#개발

# spring datasource & servlet
spring:
  application:
    name: bangdori
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none   # option type: update - 변경분만 반영(운영DB에서는 사용하면 안됨)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
  datasource:
    url: jdbc:mysql://localhost:3306/bangdori?serverTimezone=UTC&characterEncoding=UTF-8
    username: sangyong
    password: tkddyd23
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-init-sql: select 1
      validation-timeout: 2000
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 18000000
      leak-detection-threshold:  1000000

