#운영

# spring datasource & servlet
spring:
  application:
    name: bangdori
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: validate  # option type: validate - 엔티티와 테이블이 정상 매핑되었는지만 확인
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bangdori
    username: root
    password: 0000
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      connection-init-sql: select 1
      validation-timeout: 2000
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 18000000
      leak-detection-threshold:  1000000

